import express,{type Express}from"express";import{randomBytes,scrypt as sc,timingSafeEqual}from"node:crypto";import{promisify}from"node:util";import{SignJWT,jwtVerify}from"jose";import{z}from"zod";import{db,ready}from"./db.js";import{AppError}from"@readers/errors";
const scrypt=promisify(sc);export const app:Express=express();app.use(express.json());
const provinces=["A_CORUNA","ALAVA","ALBACETE","ALICANTE","ALMERIA","ASTURIAS","AVILA","BADAJOZ","BARCELONA","BIZKAIA","BURGOS","CACERES","CADIZ","CANTABRIA","CASTELLON","CEUTA","CIUDAD_REAL","CORDOBA","CUENCA","GIPUZKOA","GIRONA","GRANADA","GUADALAJARA","HUELVA","HUESCA","ILLES_BALEARS","JAEN","LA_RIOJA","LAS_PALMAS","LEON","LLEIDA","LUGO","MADRID","MALAGA","MELILLA","MURCIA","NAVARRA","OURENSE","PALENCIA","PONTEVEDRA","SALAMANCA","SANTA_CRUZ_DE_TENERIFE","SEGOVIA","SEVILLA","SORIA","TARRAGONA","TERUEL","TOLEDO","VALENCIA","VALLADOLID","ZAMORA","ZARAGOZA"]as const;
const reg=z.object({email:z.string().email(),username:z.string().min(3).max(30).regex(/^[A-Za-z0-9_]+$/),password:z.string().min(10),displayName:z.string().min(1).max(80).optional(),province:z.enum(provinces).optional()});
const secret=()=>new TextEncoder().encode(process.env.JWT_SECRET??"development-only-change-me-please-32chars");
async function hash(p:string){const salt=randomBytes(16).toString("hex");const key=await scrypt(p,salt,64)as Buffer;return`${salt}:${key.toString("hex")}`}
async function verify(p:string,v:string){const[salt,key]=v.split(":");if(!salt||!key)return false;const a=await scrypt(p,salt,64)as Buffer,b=Buffer.from(key,"hex");return a.length===b.length&&timingSafeEqual(a,b)}
async function token(id:string){return new SignJWT({sub:id}).setProtectedHeader({alg:"HS256"}).setIssuedAt().setExpirationTime("7d").sign(secret())}
app.get("/health",(_q,r)=>r.json({service:"identity",status:"ok",timestamp:new Date().toISOString()}));app.get("/ready",async(_q,r)=>{try{await ready();r.json({status:"ready"})}catch{r.status(503).json({status:"not_ready"})}});
app.post("/api/v1/auth/register",async(q,r,n)=>{try{const x=reg.parse(q.body),email=x.email.toLowerCase(),username=x.username.toLowerCase();const exists=await db.query("SELECT 1 FROM users WHERE email=$1 OR username=$2",[email,username]);if(exists.rowCount)throw new AppError(409,"USER_EXISTS","Email or username already exists");const ph=await hash(x.password);const u=await db.query('INSERT INTO users(email,username,password_hash,display_name,province)VALUES($1,$2,$3,$4,$5)RETURNING id,username,display_name AS "displayName",bio,avatar_url AS "avatarUrl",province,created_at AS "createdAt"',[email,username,ph,x.displayName??username,x.province??null]);r.status(201).json({user:u.rows[0],accessToken:await token(u.rows[0].id)})}catch(e){n(e)}});
app.post("/api/v1/auth/login",async(q,r,n)=>{try{const x=z.object({email:z.string().email(),password:z.string()}).parse(q.body);const u=await db.query("SELECT * FROM users WHERE email=$1",[x.email.toLowerCase()]);const row=u.rows[0];if(!row||!await verify(x.password,row.password_hash))throw new AppError(401,"INVALID_CREDENTIALS","Invalid credentials");r.json({user:{id:row.id,username:row.username,displayName:row.display_name,province:row.province},accessToken:await token(row.id)})}catch(e){n(e)}});
app.get("/api/v1/users/:id",async(q,r)=>{const x=await db.query('SELECT id,username,display_name AS "displayName",bio,avatar_url AS "avatarUrl",province,created_at AS "createdAt" FROM users WHERE id=$1',[q.params.id]);x.rows[0]?r.json(x.rows[0]):r.sendStatus(404)});
app.use((e:any,_q:any,r:any,_n:any)=>r.status(e instanceof AppError?e.statusCode:400).json({error:{code:e.code??"BAD_REQUEST",message:e.message}}));
