import React, { FormEvent, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { BookOpen, CalendarDays, Compass, Home, LogOut, Moon, Search, Sun, Trophy, Users } from "lucide-react";
import "./styles.css";

const API = import.meta.env.VITE_API_URL ?? "http://localhost:3000/api/v1";
type User={id:string;username:string;displayName:string;province?:string|null};
type Book={externalId:string;title:string;authors?:string[];firstPublishYear?:number|null;coverUrl?:string|null;description?:string|null;subjects?:string[]};
type Session={user:User;accessToken:string};
type View="home"|"explore"|"library"|"groups"|"clubs"|"challenges";
type LibraryItem={book_id:string;status:string;book?:Book};

async function request<T>(path:string, options:RequestInit={}, token?:string):Promise<T>{
  const headers=new Headers(options.headers); if(options.body) headers.set("Content-Type","application/json"); if(token) headers.set("Authorization",`Bearer ${token}`);
  const res=await fetch(API+path,{...options,headers}); const text=await res.text(); if(!res.ok){let message=`Error ${res.status}`;try{message=JSON.parse(text).error?.message??message}catch{}throw new Error(message)} return(text?JSON.parse(text):undefined)as T;
}
const coverFallback=(title:string)=>title.split("").reduce((a,c)=>a+c.charCodeAt(0),0)%4;
function Auth({onSession}:{onSession:(s:Session)=>void}){const[mode,setMode]=useState<"login"|"register">("login"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const data=Object.fromEntries(new FormData(e.currentTarget));try{const body=mode==="login"?{email:data.email,password:data.password}:{email:data.email,username:data.username,password:data.password,displayName:data.displayName,province:data.province};const s=await request<Session>(`/auth/${mode}`,{method:"POST",body:JSON.stringify(body)});localStorage.setItem("readers.session",JSON.stringify(s));onSession(s)}catch(x){setError(x instanceof Error?x.message:"No se pudo acceder")}finally{setBusy(false)}}
 return <div className="authShell"><section className="authStory"><div className="brand light">r<span>ea</span>ders.</div><div><p className="eyebrow">UNA COMUNIDAD PARA LEER MEJOR</p><h1>Los libros cambian cuando los compartimos.</h1><p>Descubre qué está leyendo tu gente, encuentra clubes cerca de ti y convierte cada lectura en una conversación.</p></div><small>Lee · comparte · encuentra tu próximo libro</small></section><section className="authPanel"><form className="authCard" onSubmit={submit}><p className="eyebrow">{mode==="login"?"BIENVENIDO DE NUEVO":"EMPIEZA TU BIBLIOTECA"}</p><h2>{mode==="login"?"Entra en Readers":"Crea tu cuenta"}</h2>{mode==="register"&&<><label>Nombre<input name="displayName" required placeholder="Jaime"/></label><label>Usuario<input name="username" required minLength={3} placeholder="jaime"/></label></>}<label>Email<input name="email" type="email" required placeholder="tu@email.com"/></label><label>Contraseña<input name="password" type="password" required minLength={10} placeholder="10 caracteres mínimo"/></label>{mode==="register"&&<label>Provincia<select name="province" defaultValue="SEVILLA"><option>SEVILLA</option><option>MADRID</option><option>BARCELONA</option><option>VALENCIA</option><option>CADIZ</option><option>MALAGA</option><option>GRANADA</option><option>ASTURIAS</option></select></label>}{error&&<p className="error">{error}</p>}<button className="primary" disabled={busy}>{busy?"Un momento…":mode==="login"?"Entrar":"Crear cuenta"}</button><button type="button" className="textButton" onClick={()=>setMode(mode==="login"?"register":"login")}>{mode==="login"?"¿Aún no tienes cuenta? Crear una":"Ya tengo cuenta"}</button></form></section></div>
}
function BookCard({book,onOpen}:{book:Book;onOpen:(b:Book)=>void}){return <article className="bookCard" onClick={()=>onOpen(book)}><div className={`bookCover tone${coverFallback(book.title)}`}>{book.coverUrl?<img src={book.coverUrl}/>:<span>{book.title}</span>}</div><h3>{book.title}</h3><p>{book.authors?.join(", ")||"Autor por descubrir"}</p>{book.firstPublishYear&&<small>{book.firstPublishYear}</small>}</article>}
function App(){const[session,setSession]=useState<Session|null>(()=>{try{return JSON.parse(localStorage.getItem("readers.session")||"null")}catch{return null}});const[view,setView]=useState<View>("home"),[dark,setDark]=useState(false),[query,setQuery]=useState(""),[books,setBooks]=useState<Book[]>([]),[library,setLibrary]=useState<LibraryItem[]>([]),[groups,setGroups]=useState<any[]>([]),[feed,setFeed]=useState<any[]>([]),[selected,setSelected]=useState<Book|null>(null),[loading,setLoading]=useState(false),[notice,setNotice]=useState("");
 const token=session?.accessToken; const province=session?.user.province||"SEVILLA";
 async function refresh(){if(!token)return;const [l,g,f]=await Promise.allSettled([request<any>("/me/books",{},token),request<any>(`/groups?province=${province}`,{},token),request<any>("/feed",{},token)]);if(l.status==="fulfilled"){const items:LibraryItem[]=l.value.items||[];const ids=items.map(x=>x.book_id);if(ids.length){try{const d=await request<any>(`/books/batch?ids=${encodeURIComponent(ids.join(","))}`);const m=new Map<string,Book>((d.items||[]).map((b:Book)=>[b.externalId,b]));setLibrary(items.map(x=>({...x,book:m.get(x.book_id)})))}catch{setLibrary(items)}}else setLibrary([])}if(g.status==="fulfilled")setGroups(g.value.items||[]);if(f.status==="fulfilled"){const items=f.value.items||[];const ids=[...new Set(items.map((x:any)=>x.book_id).filter(Boolean))] as string[];let m=new Map<string,Book>();if(ids.length)try{const d=await request<any>(`/books/batch?ids=${encodeURIComponent(ids.join(","))}`);m=new Map((d.items||[]).map((b:Book)=>[b.externalId,b]))}catch{}setFeed(items.map((x:any)=>({...x,book:m.get(x.book_id)})))}}
 useEffect(()=>{refresh()},[token]);
 async function search(e?:FormEvent){e?.preventDefault();if(!query.trim())return;setLoading(true);setView("explore");try{const x=await request<any>(`/books/search?q=${encodeURIComponent(query)}`);setBooks(x.items||[])}finally{setLoading(false)}}
 async function openBook(b:Book){setLoading(true);try{const detail=await request<Book>(`/books/${b.externalId}`);setSelected({...b,...detail})}finally{setLoading(false)}}
 async function shelf(status:string){if(!selected||!token)return;await request(`/me/books/${selected.externalId}`,{method:"PUT",body:JSON.stringify({status})},token);setNotice(status==="READ"?"Libro terminado. Ya puedes valorarlo.":status==="READING"?"Añadido a tus lecturas actuales.":"Guardado para más tarde.");await refresh()}
 function logout(){localStorage.removeItem("readers.session");setSession(null)}
 if(!session)return <Auth onSession={setSession}/>;
 const nav:[View,string,React.ReactNode][]=[["home","Inicio",<Home/>],["explore","Explorar",<Compass/>],["library","Mi biblioteca",<BookOpen/>],["groups","Grupos",<Users/>],["clubs","Clubes",<CalendarDays/>],["challenges","Retos",<Trophy/>]];
 return <div className={dark?"app dark":"app"}><aside><div className="brand">r<span>ea</span>ders.</div><nav>{nav.map(([id,label,icon])=><button className={view===id?"active":""} onClick={()=>setView(id)} key={id}>{icon}{label}</button>)}</nav><div className="asideBottom"><button onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}{dark?"Modo claro":"Modo oscuro"}</button><button onClick={logout}><LogOut/>Salir</button></div></aside><main><header><div><p className="eyebrow">{province.replaceAll("_"," ")}</p><h1>{view==="home"?`Hola, ${session.user.displayName}.`:nav.find(n=>n[0]===view)?.[1]}</h1></div><form className="topSearch" onSubmit={search}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Busca un libro, autor…"/></form><div className="avatar">{session.user.displayName.slice(0,2).toUpperCase()}</div></header>
 {view==="home"&&<><section className="hero"><div><p className="eyebrow">TU COMUNIDAD DE LECTORES</p><h2>¿Qué estamos<br/>leyendo?</h2><p className="muted">Tu biblioteca es solo el principio. Descubre libros a través de las personas, conversaciones y clubes que tienes cerca.</p><button onClick={()=>setView("explore")}>Encontrar mi próxima lectura →</button></div><div className="heroStack"><div className="miniBook a">2666</div><div className="miniBook b">BELoved</div><div className="miniBook c">LE GUIN</div></div></section><div className="sectionTitle"><div><p className="eyebrow">ACTIVIDAD</p><h2>Tu círculo</h2></div><span>{feed.length} publicaciones</span></div>{feed.length?<section className="feed">{feed.slice(0,4).map(p=><article key={p.id}><div className="avatar small">R</div><div><b>Un lector de tu comunidad</b><p>{p.text}</p>{p.book_id&&<small>Sobre · {p.book?.title||"libro"}</small>}</div></article>)}</section>:<Empty title="Tu círculo está tranquilo" text="Sigue lectores y únete a grupos para que sus conversaciones aparezcan aquí."/>}<section className="dashboardGrid"><div><div className="sectionTitle"><h2>Tu biblioteca</h2><button onClick={()=>setView("library")}>Ver todo →</button></div><div className="statCard"><strong>{library.length}</strong><span>libros guardados</span><p>{library.filter(x=>x.status==="READING").length} leyendo ahora · {library.filter(x=>x.status==="READ").length} terminados</p></div></div><div><div className="sectionTitle"><h2>Grupos cerca de ti</h2><button onClick={()=>setView("groups")}>Explorar →</button></div><div className="statCard"><strong>{groups.length}</strong><span>comunidades en {province.replaceAll("_"," ")}</span><p>Encuentra conversaciones y próximos encuentros.</p></div></div></section></>}
 {view==="explore"&&<><section className="pageIntro"><p className="eyebrow">CATÁLOGO · OPEN LIBRARY</p><h2>Encuentra algo que merezca tu tiempo.</h2><form className="bigSearch" onSubmit={search}><Search/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Título, autor…"/><button>Buscar</button></form></section>{loading?<p>Cargando…</p>:books.length?<section className="books">{books.map(b=><BookCard key={b.externalId} book={b} onOpen={openBook}/>)}</section>:<Empty title="Busca sin prisa" text="Prueba con un libro que te guste, un autor o ese título que llevas meses queriendo leer."/>}</>}
 {view==="library"&&<><div className="sectionTitle"><div><p className="eyebrow">PERSONAL</p><h2>Tu biblioteca</h2></div><span>{library.length} libros</span></div>{library.length?<section className="libraryShelves">{(["READING","WANT_TO_READ","READ"] as const).map(status=>{const items=library.filter(x=>x.status===status);if(!items.length)return null;return <div className="shelf" key={status}><h3>{status==="READING"?"Leyendo":status==="READ"?"Leídos":"Quiero leer"}</h3><div className="shelfBooks">{items.map(x=><article key={x.book_id} onClick={()=>x.book&&openBook(x.book)}><div className="shelfCover">{x.book?.coverUrl?<img src={x.book.coverUrl}/>:<BookOpen/>}</div><div><b>{x.book?.title||"Libro"}</b><p>{x.book?.authors?.join(", ")||""}</p></div></article>)}</div></div>})}</section>:<Empty title="Tu biblioteca está esperando" text="Busca tu primer libro y decide si quieres leerlo, lo estás leyendo o ya lo has terminado."/>}</>}
 {view==="groups"&&<><div className="sectionTitle"><div><p className="eyebrow">COMUNIDAD · {province}</p><h2>Grupos</h2></div></div>{groups.length?<section className="groupGrid">{groups.map(g=><article key={g.id}><small>{g.province||"ONLINE"}</small><h3>{g.name}</h3><p>{g.description}</p><button>Entrar al grupo →</button></article>)}</section>:<Empty title="Todavía no hay grupos aquí" text="Cuando aparezcan comunidades públicas en tu provincia las encontrarás en este espacio."/>}</>}
 {view==="clubs"&&<Empty title="Clubes de lectura, alrededor de cada libro" text="La siguiente capa conectará los eventos ya disponibles en Community con descubrimiento por libro y provincia."/>}
 {view==="challenges"&&<Empty title="Convierte una intención en hábito" text="Los retos ya existen en backend. Aquí construiremos su seguimiento visual y comunitario."/>}
 </main>{selected&&<div className="modalBackdrop" onClick={()=>setSelected(null)}><section className="bookModal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}>×</button><div className="modalCover">{selected.coverUrl?<img src={selected.coverUrl}/>:selected.title}</div><div><p className="eyebrow">LIBRO</p><h2>{selected.title}</h2><p className="author">{selected.authors?.join(", ")}</p><p className="description">{selected.description||"Open Library no tiene todavía una descripción para esta obra."}</p><div className="shelfActions"><button onClick={()=>shelf("WANT_TO_READ")}>Quiero leer</button><button className="primary" onClick={()=>shelf("READING")}>Empezar</button><button onClick={()=>shelf("READ")}>Ya lo he leído</button></div>{notice&&<p className="success">{notice}</p>}</div></section></div>}</div>
}
function Empty({title,text}:{title:string;text:string}){return <section className="empty"><BookOpen/><h3>{title}</h3><p>{text}</p></section>}
createRoot(document.getElementById("root")!).render(<App/>);
