export type HealthResponse={service:string;status:"ok";timestamp:string};
export type Rating=1|1.5|2|2.5|3|3.5|4|4.5|5;
export type ReadingStatus="WANT_TO_READ"|"READING"|"READ";
export type Province="A_CORUNA"|"ALAVA"|"ALBACETE"|"ALICANTE"|"ALMERIA"|"ASTURIAS"|"AVILA"|"BADAJOZ"|"BARCELONA"|"BIZKAIA"|"BURGOS"|"CACERES"|"CADIZ"|"CANTABRIA"|"CASTELLON"|"CEUTA"|"CIUDAD_REAL"|"CORDOBA"|"CUENCA"|"GIPUZKOA"|"GIRONA"|"GRANADA"|"GUADALAJARA"|"HUELVA"|"HUESCA"|"ILLES_BALEARS"|"JAEN"|"LA_RIOJA"|"LAS_PALMAS"|"LEON"|"LLEIDA"|"LUGO"|"MADRID"|"MALAGA"|"MELILLA"|"MURCIA"|"NAVARRA"|"OURENSE"|"PALENCIA"|"PONTEVEDRA"|"SALAMANCA"|"SANTA_CRUZ_DE_TENERIFE"|"SEGOVIA"|"SEVILLA"|"SORIA"|"TARRAGONA"|"TERUEL"|"TOLEDO"|"VALENCIA"|"VALLADOLID"|"ZAMORA"|"ZARAGOZA";
