import express,{type Express}from"express";import{z}from"zod";import{db,ready}from"./db.js";export const app:Express=express();app.use(express.json());const uid=(q:any)=>String(q.header("x-user-id")??"");const rating=z.number().min(1).max(5).refine(v=>Number.isInteger(v*2));
app.get("/health",(_q,r)=>r.json({service:"reading",status:"ok",timestamp:new Date().toISOString()}));app.get("/ready",async(_q,r)=>{try{await ready();r.json({status:"ready"})}catch{r.status(503).json({status:"not_ready"})}});
app.put("/api/v1/me/books/:bookId",async(q,r)=>{const x=z.object({status:z.enum(["WANT_TO_READ","READING","READ"])}).parse(q.body),now=new Date();const started=x.status==="READING"?now:null,finished=x.status==="READ"?now:null;const y=await db.query('INSERT INTO user_books(user_id,book_id,status,started_at,finished_at)VALUES($1,$2,$3,$4,$5)ON CONFLICT(user_id,book_id)DO UPDATE SET status=$3,started_at=COALESCE(user_books.started_at,$4),finished_at=$5,updated_at=NOW() RETURNING *',[uid(q),q.params.bookId,x.status,started,finished]);r.json(y.rows[0])});
app.get("/api/v1/me/books",async(q,r)=>r.json({items:(await db.query("SELECT * FROM user_books WHERE user_id=$1 ORDER BY updated_at DESC",[uid(q)])).rows}));
app.put("/api/v1/books/:bookId/review",async(q,r)=>{const x=z.object({rating,text:z.string().max(10000).optional(),spoiler:z.boolean().default(false)}).parse(q.body);const y=await db.query('INSERT INTO reviews(user_id,book_id,rating,text,spoiler)VALUES($1,$2,$3,$4,$5)ON CONFLICT(user_id,book_id)DO UPDATE SET rating=$3,text=$4,spoiler=$5,updated_at=NOW() RETURNING *',[uid(q),q.params.bookId,rating.parse(x.rating),x.text??null,x.spoiler]);r.json(y.rows[0])});
app.get("/api/v1/books/:bookId/reviews",async(q,r)=>r.json({items:(await db.query("SELECT r.*,COUNT(DISTINCT l.user_id)::int AS likes,COUNT(DISTINCT c.id)::int AS comments,BOOL_OR(l.user_id=$2::uuid) AS liked_by_me FROM reviews r LEFT JOIN review_likes l ON l.review_id=r.id LEFT JOIN review_comments c ON c.review_id=r.id WHERE r.book_id=$1 GROUP BY r.id ORDER BY r.created_at DESC",[q.params.bookId,uid(q)||null])).rows}));
app.post("/api/v1/reviews/:id/like",async(q,r)=>{await db.query("INSERT INTO review_likes(review_id,user_id)VALUES($1,$2)ON CONFLICT DO NOTHING",[q.params.id,uid(q)]);r.sendStatus(204)});app.delete("/api/v1/reviews/:id/like",async(q,r)=>{await db.query("DELETE FROM review_likes WHERE review_id=$1 AND user_id=$2",[q.params.id,uid(q)]);r.sendStatus(204)});
app.post("/api/v1/reviews/:id/comments",async(q,r)=>{const text=z.string().min(1).max(2000).parse(q.body.text);const x=await db.query("INSERT INTO review_comments(review_id,user_id,text)VALUES($1,$2,$3)RETURNING *",[q.params.id,uid(q),text]);r.status(201).json(x.rows[0])});app.get("/api/v1/reviews/:id/comments",async(q,r)=>r.json({items:(await db.query("SELECT * FROM review_comments WHERE review_id=$1 ORDER BY created_at",[q.params.id])).rows}));
app.get("/api/v1/recommendations",async(q,r)=>{const x=await db.query("SELECT book_id,AVG(rating)::numeric(2,1) score,COUNT(*)::int ratings FROM reviews WHERE book_id NOT IN(SELECT book_id FROM user_books WHERE user_id=$1) GROUP BY book_id HAVING COUNT(*)>=1 ORDER BY AVG(rating) DESC,COUNT(*) DESC LIMIT 20",[uid(q)]);r.json({strategy:"collaborative-ready-v1",items:x.rows})});
