CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE users(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),email VARCHAR(320) UNIQUE NOT NULL,username VARCHAR(30) UNIQUE NOT NULL,password_hash TEXT NOT NULL,display_name VARCHAR(80) NOT NULL,bio VARCHAR(500),avatar_url TEXT,province VARCHAR(32),created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
